export const en = {
  nav: { overview: "Overview", manage: "Manage", codex: "Codex", tools: "Tools", preferences: "Preferences", dashboard: "Dashboard", conversations: "Conversations", backup: "Backup & Restore", skills: "Skills", pets: "Pets", diagnostics: "Diagnostics", settings: "Settings", primary: "Primary navigation", localFoundation: "Local-only foundation · v0.1.0" },
  common: { working: "Working…", refreshing: "Refreshing…", refresh: "Refresh", save: "Save settings", loading: "Loading settings…", unavailable: "Unavailable", notFound: "Not found", available: "Available", yes: "Yes", no: "No", dash: "—", errorLoad: "Unable to load data.", errorOperation: "The operation could not be completed." },
  settings: { title: "Settings", description: "Local preferences for Codex Companion.", language: "Language", english: "English", vietnamese: "Tiếng Việt", theme: "Theme", system: "System", light: "Light", dark: "Dark", logLevel: "Log level", error: "Error", warn: "Warning", info: "Info", debug: "Debug", portable: "Enable portable mode when supported", safety: "Create safety backups before restore when existing session files conflict" },
  dashboard: { title: "Dashboard", description: "A lightweight control panel for your local Codex environment.", environment: "Codex environment", detected: "Detected", notDetected: "Not detected", skills: "Installed skills", pets: "Installed pets", backups: "Backups", comingSoon: "Coming soon", summary: "Environment summary", safe: "Safe by design", safeText: "Codex Companion reads local metadata and only writes session files through an explicit, validated restore workflow." },
  conversations: { title: "Conversations", description: "Read-only discovery of local Codex session metadata. Conversation content is never loaded.", unavailableTitle: "Sessions are unavailable", unavailableHome: "Codex home was not found. Set CODEX_HOME or install Codex before refreshing.", unavailableDirectory: "Codex home was found, but it has no legacy sessions directory yet.", unavailablePermission: "Companion does not have permission to read the local Codex session directory.", unavailableFilesystem: "The local session directory could not be read. Check that it is available and try again.", discoveryError: "Unable to discover conversations: {error}", found: "Sessions found", ready: "Ready to display", skipped: "Skipped", unsupported: "Unsupported", filters: "Conversation filters", search: "Search", searchPlaceholder: "Title, project, path, or ID", project: "Project", sort: "Sort", allProjects: "All projects", updated: "Last updated", created: "Created", titleColumn: "Title", source: "Source", noSessions: "No conversations found", noMatching: "No matching conversations", noSessionsDescription: "No readable legacy rollout sessions were found in the local Codex sessions directory.", noMatchingDescription: "Adjust the search or project filter to see discovered sessions.", untitled: "Untitled session" },
  backup: { title: "Backup & Restore", description: "Create a versioned ZIP from sessions you select, or safely restore an inspected archive.", discover: "Discover sessions", chooseConversations: "Choose conversations to export", chooseDescription: "Discover local session metadata, select one or more sessions, then review the exact archive summary before creating it.", unavailableTitle: "Sessions are unavailable", unavailableDescription: "Backup requires readable legacy sessions discovered from the local Codex sessions directory.", selectConversations: "Select conversations", selected: "{count} selected", localOnly: "Session contents stay local until you create the archive.", previewBackup: "Preview backup", createBackup: "Create backup archive", noSessions: "No conversations found", noSessionsDescription: "There are no readable legacy sessions available to export.", select: "Select", conversation: "Conversation", project: "Project", updated: "Updated", backupPreview: "Backup preview", formatSummary: "Format v{version} · {count} session(s) · {bytes}", destinationFolder: "Destination folder", archiveContents: "Archive contents", archiveContentsValue: "manifest.json and exactly {count} selected session file(s)", backupCreated: "Backup created", exported: "{count} selected session(s) exported ({bytes}).", inspect: "Inspect a backup archive", inspectDescription: "Choose a ZIP created by Companion to validate its manifest and exact session entries. Inspection never extracts or changes the archive.", choose: "Choose ZIP archive", valid: "Archive is valid", invalid: "Archive needs attention", archiveSummary: "format {format} · {count} session(s) · {bytes}", created: "Created", platform: "Platform", cli: "Codex CLI", notRecorded: "Not recorded", manifestValidation: "Manifest validation", passed: "Passed", failed: "Failed", warnings: "Warnings", errors: "Errors", restoreSelect: "Select sessions to restore", previewRestore: "Preview restore", restore: "Restore selected sessions", destination: "Destination", conflicts: "Existing files (skipped)", planned: "Planned create-new copies", safety: "A versioned safety backup of conflicting regular files will be created first.", noSafety: "No safety backup is needed because restore never overwrites files or has no conflicts.", restored: "Restore completed", restoredSummary: "{restored} restored · {skipped} existing files skipped", error: "The operation could not be completed." },
  diagnostics: { title: "Diagnostics", description: "Read-only checks for the local Codex environment.", operatingSystem: "Operating system", architecture: "Architecture", codexHome: "Codex home", codexHomeStatus: "Codex home status", cli: "Codex CLI", config: "Companion configuration", backupDir: "Backup directory", skills: "Installed skills", pets: "Installed pets", none: "No diagnostics are available." },
  skills: { title: "Skills", description: "Custom Codex skills detected on this computer.", planned: "Skills management is planned", detail: "The diagnostics page reports an aggregate count only; individual skill contents remain untouched.", next: "Add a read-only metadata list and explicit import/export flows." },
  pets: { title: "Pets", description: "Manage custom Codex pets independently from other data.", planned: "Pets management is planned", detail: "This milestone detects only the configured pets directory and never installs or removes a pet.", next: "Add validated pet metadata previews and explicit install/remove confirmation." },
  empty: { milestone: "Milestone 4 foundation", next: "Next: {step}", status: "{title} status" }
} as const;

export type TranslationDictionary = { [Section in keyof typeof en]: { [Item in keyof (typeof en)[Section]]: string } };
