import type { TranslationDictionary } from "./en";

export const vi: TranslationDictionary = {
  nav: { overview: "Tổng quan", manage: "Quản lý", codex: "Codex", tools: "Công cụ", preferences: "Tùy chọn", dashboard: "Bảng điều khiển", conversations: "Phiên trò chuyện", backup: "Sao lưu & Khôi phục", skills: "Kỹ năng", pets: "Thú cưng", diagnostics: "Chẩn đoán", settings: "Cài đặt", primary: "Điều hướng chính", localFoundation: "Nền tảng chỉ cục bộ · v0.1.0" },
  common: { working: "Đang xử lý…", refreshing: "Đang làm mới…", refresh: "Làm mới", save: "Lưu cài đặt", loading: "Đang tải cài đặt…", unavailable: "Không có", notFound: "Không tìm thấy", available: "Sẵn sàng", yes: "Có", no: "Không", dash: "—", errorLoad: "Không thể tải dữ liệu.", errorOperation: "Không thể hoàn tất thao tác." },
  settings: { title: "Cài đặt", description: "Tùy chọn cục bộ của Codex Companion.", language: "Ngôn ngữ", english: "English", vietnamese: "Tiếng Việt", theme: "Giao diện", system: "Theo hệ thống", light: "Sáng", dark: "Tối", logLevel: "Mức nhật ký", error: "Lỗi", warn: "Cảnh báo", info: "Thông tin", debug: "Gỡ lỗi", portable: "Bật chế độ portable khi được hỗ trợ", safety: "Tạo bản sao lưu an toàn trước khi khôi phục nếu có file phiên trùng" },
  dashboard: { title: "Bảng điều khiển", description: "Bảng điều khiển gọn nhẹ cho môi trường Codex cục bộ.", environment: "Môi trường Codex", detected: "Đã phát hiện", notDetected: "Chưa phát hiện", skills: "Kỹ năng đã cài", pets: "Thú cưng đã cài", backups: "Sao lưu", comingSoon: "Sắp có", summary: "Tóm tắt môi trường", safe: "An toàn ngay từ thiết kế", safeText: "Codex Companion đọc metadata cục bộ và chỉ ghi file phiên qua luồng khôi phục rõ ràng, đã kiểm tra." },
  conversations: { title: "Phiên trò chuyện", description: "Khám phá chỉ đọc metadata phiên Codex cục bộ. Nội dung trò chuyện không bao giờ được tải.", unavailableTitle: "Không thể dùng phiên", unavailableHome: "Không tìm thấy Codex home. Hãy đặt CODEX_HOME hoặc cài Codex trước khi làm mới.", unavailableDirectory: "Đã tìm thấy Codex home nhưng chưa có thư mục phiên legacy.", unavailablePermission: "Companion không có quyền đọc thư mục phiên Codex cục bộ.", unavailableFilesystem: "Không thể đọc thư mục phiên cục bộ. Hãy kiểm tra thư mục rồi thử lại.", discoveryError: "Không thể khám phá phiên trò chuyện: {error}", found: "Đã tìm thấy", ready: "Sẵn sàng hiển thị", skipped: "Đã bỏ qua", unsupported: "Không hỗ trợ", filters: "Bộ lọc phiên trò chuyện", search: "Tìm kiếm", searchPlaceholder: "Tiêu đề, dự án, đường dẫn hoặc ID", project: "Dự án", sort: "Sắp xếp", allProjects: "Tất cả dự án", updated: "Cập nhật gần nhất", created: "Đã tạo", titleColumn: "Tiêu đề", source: "Nguồn", noSessions: "Không tìm thấy phiên", noMatching: "Không có phiên phù hợp", noSessionsDescription: "Không tìm thấy phiên rollout legacy có thể đọc trong thư mục phiên Codex cục bộ.", noMatchingDescription: "Hãy điều chỉnh tìm kiếm hoặc bộ lọc dự án để xem các phiên đã phát hiện.", untitled: "Phiên chưa đặt tên" },
  backup: { title: "Sao lưu & Khôi phục", description: "Tạo ZIP có phiên bản từ các phiên đã chọn, hoặc khôi phục an toàn archive đã kiểm tra.", discover: "Tìm phiên", chooseConversations: "Chọn phiên để xuất", chooseDescription: "Khám phá metadata phiên cục bộ, chọn một hoặc nhiều phiên, rồi xem đúng nội dung archive trước khi tạo.", unavailableTitle: "Không thể dùng phiên", unavailableDescription: "Sao lưu cần các phiên legacy có thể đọc được từ thư mục phiên Codex cục bộ.", selectConversations: "Chọn phiên trò chuyện", selected: "Đã chọn {count}", localOnly: "Nội dung phiên luôn ở cục bộ cho tới khi bạn tạo archive.", previewBackup: "Xem trước sao lưu", createBackup: "Tạo archive sao lưu", noSessions: "Không tìm thấy phiên", noSessionsDescription: "Không có phiên legacy có thể đọc để xuất.", select: "Chọn", conversation: "Phiên trò chuyện", project: "Dự án", updated: "Cập nhật", backupPreview: "Xem trước sao lưu", formatSummary: "Định dạng v{version} · {count} phiên · {bytes}", destinationFolder: "Thư mục đích", archiveContents: "Nội dung archive", archiveContentsValue: "manifest.json và chính xác {count} file phiên đã chọn", backupCreated: "Đã tạo bản sao lưu", exported: "Đã xuất {count} phiên đã chọn ({bytes}).", inspect: "Kiểm tra archive sao lưu", inspectDescription: "Chọn ZIP do Companion tạo để xác thực manifest và chính xác các phiên. Việc kiểm tra không giải nén hoặc thay đổi archive.", choose: "Chọn archive ZIP", valid: "Archive hợp lệ", invalid: "Archive cần chú ý", archiveSummary: "định dạng {format} · {count} phiên · {bytes}", created: "Đã tạo", platform: "Nền tảng", cli: "Codex CLI", notRecorded: "Chưa ghi nhận", manifestValidation: "Xác thực manifest", passed: "Đạt", failed: "Không đạt", warnings: "Cảnh báo", errors: "Lỗi", restoreSelect: "Chọn phiên để khôi phục", previewRestore: "Xem trước khôi phục", restore: "Khôi phục các phiên đã chọn", destination: "Đích", conflicts: "File đã có (bỏ qua)", planned: "Số bản sao tạo mới", safety: "Bản sao lưu an toàn có phiên bản của các file thường bị trùng sẽ được tạo trước.", noSafety: "Không cần backup an toàn vì khôi phục không ghi đè file hoặc không có file trùng.", restored: "Khôi phục hoàn tất", restoredSummary: "Đã khôi phục {restored} · bỏ qua {skipped} file đã có", error: "Không thể hoàn tất thao tác." },
  diagnostics: { title: "Chẩn đoán", description: "Kiểm tra chỉ đọc cho môi trường Codex cục bộ.", operatingSystem: "Hệ điều hành", architecture: "Kiến trúc", codexHome: "Codex home", codexHomeStatus: "Trạng thái Codex home", cli: "Codex CLI", config: "Cấu hình Companion", backupDir: "Thư mục sao lưu", skills: "Kỹ năng đã cài", pets: "Thú cưng đã cài", none: "Không có dữ liệu chẩn đoán." },
  skills: { title: "Kỹ năng", description: "Kỹ năng Codex tùy chỉnh được phát hiện trên máy này.", planned: "Quản lý kỹ năng đang được lên kế hoạch", detail: "Trang chẩn đoán chỉ báo số lượng tổng; nội dung kỹ năng riêng lẻ vẫn không bị chạm tới.", next: "Thêm danh sách metadata chỉ đọc và luồng nhập/xuất minh bạch." },
  pets: { title: "Thú cưng", description: "Quản lý thú cưng Codex tùy chỉnh độc lập với dữ liệu khác.", planned: "Quản lý thú cưng đang được lên kế hoạch", detail: "Milestone này chỉ phát hiện thư mục thú cưng đã cấu hình và không cài hay gỡ bất kỳ thú cưng nào.", next: "Thêm xem trước metadata thú cưng đã xác thực và xác nhận cài/gỡ rõ ràng." },
  empty: { milestone: "Nền tảng Milestone 4", next: "Tiếp theo: {step}", status: "Trạng thái {title}" }
};
