import { useCallback, useMemo, useState } from "react";
import { PageHeader } from "../../components/PageHeader";
import { useTranslation } from "../../i18n";
import { createBackup, discoverConversations, inspectBackupArchive, previewBackup, previewRestore, restoreArchive } from "../../services/tauri";
import type { ArchiveInspection, BackupPreview, BackupResult, ConversationDiscovery, RestorePreview, RestoreResult } from "../../types/codex";

function formatBytes(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

export function BackupPage() {
  const { t } = useTranslation();
  const [discovery, setDiscovery] = useState<ConversationDiscovery | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState<BackupPreview | null>(null); const [previewIds, setPreviewIds] = useState<string[]>([]); const [result, setResult] = useState<BackupResult | null>(null); const [inspection, setInspection] = useState<ArchiveInspection | null>(null); const [restoreSelected, setRestoreSelected] = useState<Set<string>>(new Set()); const [restorePreviewState, setRestorePreviewState] = useState<RestorePreview | null>(null); const [restoreResult, setRestoreResult] = useState<RestoreResult | null>(null);
  const selectedIds = useMemo(() => [...selected].sort(), [selected]); const restoreIds = useMemo(() => [...restoreSelected].sort(), [restoreSelected]);
  const refresh = useCallback(async () => { setLoading(true); setError(null); setPreview(null); setResult(null); try { setDiscovery(await discoverConversations()); setSelected(new Set()); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } }, []);
  const toggle = (id: string) => { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); setPreview(null); setResult(null); };
  const showPreview = async () => { setLoading(true); setError(null); try { setPreview(await previewBackup(selectedIds)); setPreviewIds(selectedIds); } catch (reason) { setError(String(reason)); setPreview(null); } finally { setLoading(false); } };
  const create = async () => { setLoading(true); setError(null); try { setResult(await createBackup(selectedIds)); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } };
  const chooseArchive = async () => { setLoading(true); setError(null); try { setInspection(await inspectBackupArchive()); setRestoreSelected(new Set()); setRestorePreviewState(null); setRestoreResult(null); } catch { setInspection(null); setError(t("backup.error")); } finally { setLoading(false); } };
  const showRestorePreview = async () => { if (!inspection?.restoreToken) return; setLoading(true); setError(null); try { setRestorePreviewState(await previewRestore(inspection.restoreToken, restoreIds)); } catch { setError(t("backup.error")); } finally { setLoading(false); } };
  const restore = async () => { if (!inspection?.restoreToken) return; setLoading(true); setError(null); try { setRestoreResult(await restoreArchive(inspection.restoreToken, restoreIds)); } catch { setError(t("backup.error")); } finally { setLoading(false); } };
  const previewCurrent = preview !== null && previewIds.join("\u0000") === selectedIds.join("\u0000");
  return <>
    <PageHeader title={t("backup.title")} description={t("backup.description")} action={<button type="button" onClick={() => void refresh()} disabled={loading}>{loading ? t("common.working") : t("backup.discover")}</button>} />
    {error && <p className="error-banner">{error}</p>}
    {!discovery && !loading && <section className="notice-card"><h2>{t("backup.chooseConversations")}</h2><p>{t("backup.chooseDescription")}</p></section>}
    {discovery && discovery.status !== "ready" && <section className="notice-card"><h2>{t("backup.unavailableTitle")}</h2><p>{t("backup.unavailableDescription")}</p></section>}
    {discovery?.status === "ready" && <><section className="backup-selection"><div><h2>{t("backup.selectConversations")}</h2><p>{t("backup.selected", { count: selectedIds.length })} · {t("backup.localOnly")}</p></div><button type="button" onClick={() => void showPreview()} disabled={loading || selectedIds.length === 0}>{t("backup.previewBackup")}</button></section>{discovery.conversations.length === 0 ? <section className="notice-card"><h2>{t("backup.noSessions")}</h2><p>{t("backup.noSessionsDescription")}</p></section> : <section className="conversation-table-wrap"><table className="conversation-table backup-table"><thead><tr><th aria-label={t("backup.select")} /><th>{t("backup.conversation")}</th><th>{t("backup.project")}</th><th>{t("backup.updated")}</th></tr></thead><tbody>{discovery.conversations.map((conversation) => <tr key={conversation.id}><td><input aria-label={`${t("backup.select")} ${conversation.title || conversation.id}`} type="checkbox" checked={selected.has(conversation.id)} onChange={() => toggle(conversation.id)} /></td><td><strong>{conversation.title || t("conversations.untitled")}</strong><code>{conversation.id}</code></td><td>{conversation.projectName || t("common.dash")}</td><td>{conversation.updatedAt || conversation.createdAt || t("common.dash")}</td></tr>)}</tbody></table></section>}</>}
    {previewCurrent && <section className="backup-preview"><h2>{t("backup.backupPreview")}</h2><p>{t("backup.formatSummary", { version: preview.formatVersion, count: preview.sessionCount, bytes: formatBytes(preview.totalBytes) })}</p><dl><div><dt>{t("backup.destinationFolder")}</dt><dd><code>{preview.backupDirectory}</code></dd></div><div><dt>{t("backup.archiveContents")}</dt><dd>{t("backup.archiveContentsValue", { count: preview.sessionCount })}</dd></div></dl><button type="button" onClick={() => void create()} disabled={loading}>{t("backup.createBackup")}</button></section>}
    {result && <section className="success-card"><h2>{t("backup.backupCreated")}</h2><p>{t("backup.exported", { count: result.sessionCount, bytes: formatBytes(result.totalBytes) })}</p><code>{result.archivePath}</code></section>}
    <section className="archive-inspection"><div><h2>{t("backup.inspect")}</h2><p>{t("backup.inspectDescription")}</p></div><button type="button" onClick={() => void chooseArchive()} disabled={loading}>{loading ? t("common.working") : t("backup.choose")}</button></section>
    {inspection && <section className={inspection.validation.valid ? "inspection-result valid" : "inspection-result invalid"}><h2>{inspection.validation.valid ? t("backup.valid") : t("backup.invalid")}</h2><p><strong>{inspection.archiveName}</strong> · {t("backup.archiveSummary", { format: inspection.validation.formatVersion === null ? t("common.unavailable") : `v${inspection.validation.formatVersion}`, count: inspection.sessionCount, bytes: formatBytes(inspection.totalBytes) })}</p><dl><div><dt>{t("backup.created")}</dt><dd>{inspection.createdAt || t("common.unavailable")}</dd></div><div><dt>{t("backup.platform")}</dt><dd>{inspection.platform || t("common.unavailable")}</dd></div><div><dt>{t("backup.cli")}</dt><dd>{inspection.codexCliVersion || t("backup.notRecorded")}</dd></div><div><dt>{t("backup.manifestValidation")}</dt><dd>{inspection.validation.valid ? t("backup.passed") : t("backup.failed")}</dd></div></dl>{inspection.warnings.length > 0 && <div className="inspection-messages warnings"><h3>{t("backup.warnings")}</h3><ul>{inspection.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}{inspection.errors.length > 0 && <div className="inspection-messages errors"><h3>{t("backup.errors")}</h3><ul>{inspection.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}</section>}
    {inspection?.validation.valid && inspection.restoreToken && <section className="restore-panel"><div><h2>{t("backup.restoreSelect")}</h2><p>{t("backup.select")}</p></div><div className="restore-list">{inspection.sessions.map((session) => <label key={session.id}><input type="checkbox" checked={restoreSelected.has(session.id)} onChange={() => setRestoreSelected((current) => { const next = new Set(current); if (next.has(session.id)) next.delete(session.id); else next.add(session.id); return next; })} /> {session.title || session.id} <code>{session.archivePath}</code></label>)}</div><button type="button" onClick={() => void showRestorePreview()} disabled={loading || restoreIds.length === 0}>{t("backup.previewRestore")}</button></section>}
    {restorePreviewState && <section className="backup-preview"><h2>{t("backup.previewRestore")}</h2><p>{t("backup.formatSummary", { version: 1, count: restorePreviewState.sessionCount, bytes: formatBytes(restorePreviewState.totalBytes) })}</p><dl><div><dt>{t("backup.destination")}</dt><dd><code>{restorePreviewState.destinationRoot}</code></dd></div><div><dt>{t("backup.conflicts")}</dt><dd>{restorePreviewState.conflictCount}</dd></div><div><dt>{t("backup.planned")}</dt><dd>{restorePreviewState.plannedCreates}</dd></div></dl><p>{restorePreviewState.safetyBackupWillBeCreated ? t("backup.safety") : t("backup.noSafety")}</p><button type="button" onClick={() => void restore()} disabled={loading}>{t("backup.restore")}</button></section>}
    {restoreResult && <section className="success-card"><h2>{t("backup.restored")}</h2><p>{t("backup.restoredSummary", { restored: restoreResult.restoredCount, skipped: restoreResult.skippedConflicts })}</p>{restoreResult.safetyBackupPath && <code>{restoreResult.safetyBackupPath}</code>}</section>}
  </>;
}
